### ISSUE TITLE
Bug Report: Game doesn't Boot

### ISSUE THREAD

**Issue by mcJofsel** [General-Infinity/TrollEngine#1]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86_64`)

## Please describe your issue. Provide extensive detail and images if possible.
It isn't starting up.

**Comment by Hendicted** [comment]
i'll be diagnosing that, i'd suspect its some sort of save data thing

**Comment by Hendicted** [comment]
Update: it had something to do with the framerate being set to null, whoops!

**Comment by mcJofsel** [comment]
Thanks for replying! I'll get to fixing that in my folder too.

**Comment by Hendicted** [comment]
> 
> 
> Thanks for replying! I'll get to fixing that in my folder too.
Here's another update, the executable on gamebanana has been updated with the fix. enjoy!

**Comment by mcJofsel** [comment]
Hope you send the update to the source code, too.
