### ISSUE TITLE
Bug Report: I can't recompile the game

### ISSUE THREAD

**Issue by DestenyLink2121** [General-Infinity/TrollEngine#3]
So I was using the troll engine for coding instead of the default one and I got done but when i tried to recompile it it said:

Error: Could not find haxelib "datetime", does it need to be installed?

So I'm pretty sure you forgot to put that part in the source code

**Comment by Hendicted** [comment]
apparently i forgot to remove the obsolete lib in the Project.xml file, whoops!

just remove this line of Project.xml:
```xml
<haxelib name="datetime"/>
```
