### ISSUE TITLE
Bug Report: Recompiling issue strike back

### ISSUE THREAD

**Issue by DestenyLink2121** [General-Infinity/TrollEngine#4]
I tried to recompile the game after removing "udprotean" because I didnt have it and then it said all this:
source/MainMenuState.hx:49: characters 14-31 : Type not found : datetime.DateTime
source/ConnectSubState.hx:3: characters 8-40 : Type not found : udprotean.client.UDProteanClient
source/ChatState.hx:12: characters 8-40 : Type not found : udprotean.client.UDProteanClient
source/ConnectSubState.hx:5: characters 25-40 : Type not found : UDProteanClient
source/MainMenuState.hx:22: lines 22-239 : Defined in this class
source/ConnectSubState.hx:5: characters 25-40 : Type not found : UDProteanClient
source/ChatState.hx:15: lines 15-70 : Defined in this class
source/ChatState.hx:28: characters 16-23 : NetClient has no field connect
source/ChatState.hx:60: characters 16-22 : NetClient has no field update
source/ChatState.hx:65: characters 20-24 : NetClient has no field send
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/format/XMLMerge.hx:189: characters 10-23 : Warning : This typedef is deprecated in favor of haxe.xml.Access
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/format/XMLMerge.hx:189: characters 30-43 : Warning : This typedef is deprecated in favor of haxe.xml.Access

**Comment by Hendicted** [comment]
is the source code up to date? (type git pull in the terminal)

**Comment by DestenyLink2121** [comment]
> is the source code up to date? (type git pull in the terminal)

I tried but it said this:
'git' is not recognized as an internal or external command,
operable program or batch file.

That might be because I just downloaded the files instead of using git
